packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - "@embedded-postgres/darwin-arm64"
  - "@embedded-postgres/darwin-x64"
  - "@embedded-postgres/linux-arm64"
  - "@embedded-postgres/linux-x64"
  - "@embedded-postgres/windows-x64"
  - agent-browser

overrides:
  "@prisma/config>deepmerge-ts": 8.0.2
  "prisma>mysql2": 3.24.5
